#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_JT18")]
	public partial class LTSJT18DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_R_CONTRACTOR(TBL_R_CONTRACTOR instance);
    partial void UpdateTBL_R_CONTRACTOR(TBL_R_CONTRACTOR instance);
    partial void DeleteTBL_R_CONTRACTOR(TBL_R_CONTRACTOR instance);
    partial void InsertTBL_R_CPP(TBL_R_CPP instance);
    partial void UpdateTBL_R_CPP(TBL_R_CPP instance);
    partial void DeleteTBL_R_CPP(TBL_R_CPP instance);
    partial void InsertTBL_R_ENTITY(TBL_R_ENTITY instance);
    partial void UpdateTBL_R_ENTITY(TBL_R_ENTITY instance);
    partial void DeleteTBL_R_ENTITY(TBL_R_ENTITY instance);
    partial void InsertTBL_R_PRODUCT(TBL_R_PRODUCT instance);
    partial void UpdateTBL_R_PRODUCT(TBL_R_PRODUCT instance);
    partial void DeleteTBL_R_PRODUCT(TBL_R_PRODUCT instance);
    partial void InsertTBL_R_STOCKPILE(TBL_R_STOCKPILE instance);
    partial void UpdateTBL_R_STOCKPILE(TBL_R_STOCKPILE instance);
    partial void DeleteTBL_R_STOCKPILE(TBL_R_STOCKPILE instance);
    partial void InsertTBL_R_UNIT(TBL_R_UNIT instance);
    partial void UpdateTBL_R_UNIT(TBL_R_UNIT instance);
    partial void DeleteTBL_R_UNIT(TBL_R_UNIT instance);
    partial void InsertTBL_T_TARE_UNIT(TBL_T_TARE_UNIT instance);
    partial void UpdateTBL_T_TARE_UNIT(TBL_T_TARE_UNIT instance);
    partial void DeleteTBL_T_TARE_UNIT(TBL_T_TARE_UNIT instance);
    partial void InsertTBL_T_TRANSAKSI_18(TBL_T_TRANSAKSI_18 instance);
    partial void UpdateTBL_T_TRANSAKSI_18(TBL_T_TRANSAKSI_18 instance);
    partial void DeleteTBL_T_TRANSAKSI_18(TBL_T_TRANSAKSI_18 instance);
    #endregion
		
		public LTSJT18DataContext() : 
				base(global::WinForms.Properties.Settings.Default.DB_JT18ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LTSJT18DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSJT18DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSJT18DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LTSJT18DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_R_CONTRACTOR> TBL_R_CONTRACTORs
		{
			get
			{
				return this.GetTable<TBL_R_CONTRACTOR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_CPP> TBL_R_CPPs
		{
			get
			{
				return this.GetTable<TBL_R_CPP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_ENTITY> TBL_R_ENTITies
		{
			get
			{
				return this.GetTable<TBL_R_ENTITY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_PRODUCT> TBL_R_PRODUCTs
		{
			get
			{
				return this.GetTable<TBL_R_PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_STOCKPILE> TBL_R_STOCKPILEs
		{
			get
			{
				return this.GetTable<TBL_R_STOCKPILE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_UNIT> TBL_R_UNITs
		{
			get
			{
				return this.GetTable<TBL_R_UNIT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_TARE_UNIT> TBL_T_TARE_UNITs
		{
			get
			{
				return this.GetTable<TBL_T_TARE_UNIT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_TRANSAKSI_18> TBL_T_TRANSAKSI_18s
		{
			get
			{
				return this.GetTable<TBL_T_TRANSAKSI_18>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_CONTRACTOR")]
	public partial class TBL_R_CONTRACTOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CONTRACTOR_CODE;
		
		private string _CONTRACTOR_NAME;
		
		private string _CONTRACTOR_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONTRACTOR_CODEChanging(string value);
    partial void OnCONTRACTOR_CODEChanged();
    partial void OnCONTRACTOR_NAMEChanging(string value);
    partial void OnCONTRACTOR_NAMEChanged();
    partial void OnCONTRACTOR_AKTIFChanging(string value);
    partial void OnCONTRACTOR_AKTIFChanged();
    #endregion
		
		public TBL_R_CONTRACTOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTOR_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CONTRACTOR_CODE
		{
			get
			{
				return this._CONTRACTOR_CODE;
			}
			set
			{
				if ((this._CONTRACTOR_CODE != value))
				{
					this.OnCONTRACTOR_CODEChanging(value);
					this.SendPropertyChanging();
					this._CONTRACTOR_CODE = value;
					this.SendPropertyChanged("CONTRACTOR_CODE");
					this.OnCONTRACTOR_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTOR_NAME", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string CONTRACTOR_NAME
		{
			get
			{
				return this._CONTRACTOR_NAME;
			}
			set
			{
				if ((this._CONTRACTOR_NAME != value))
				{
					this.OnCONTRACTOR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CONTRACTOR_NAME = value;
					this.SendPropertyChanged("CONTRACTOR_NAME");
					this.OnCONTRACTOR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACTOR_AKTIF", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CONTRACTOR_AKTIF
		{
			get
			{
				return this._CONTRACTOR_AKTIF;
			}
			set
			{
				if ((this._CONTRACTOR_AKTIF != value))
				{
					this.OnCONTRACTOR_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._CONTRACTOR_AKTIF = value;
					this.SendPropertyChanged("CONTRACTOR_AKTIF");
					this.OnCONTRACTOR_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_CPP")]
	public partial class TBL_R_CPP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CPP_CODE;
		
		private string _CPP_ENTITY;
		
		private string _CPP_LOKASI;
		
		private string _CPP_DESC;
		
		private string _CPP_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPP_CODEChanging(string value);
    partial void OnCPP_CODEChanged();
    partial void OnCPP_ENTITYChanging(string value);
    partial void OnCPP_ENTITYChanged();
    partial void OnCPP_LOKASIChanging(string value);
    partial void OnCPP_LOKASIChanged();
    partial void OnCPP_DESCChanging(string value);
    partial void OnCPP_DESCChanged();
    partial void OnCPP_AKTIFChanging(string value);
    partial void OnCPP_AKTIFChanged();
    #endregion
		
		public TBL_R_CPP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPP_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CPP_CODE
		{
			get
			{
				return this._CPP_CODE;
			}
			set
			{
				if ((this._CPP_CODE != value))
				{
					this.OnCPP_CODEChanging(value);
					this.SendPropertyChanging();
					this._CPP_CODE = value;
					this.SendPropertyChanged("CPP_CODE");
					this.OnCPP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPP_ENTITY", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CPP_ENTITY
		{
			get
			{
				return this._CPP_ENTITY;
			}
			set
			{
				if ((this._CPP_ENTITY != value))
				{
					this.OnCPP_ENTITYChanging(value);
					this.SendPropertyChanging();
					this._CPP_ENTITY = value;
					this.SendPropertyChanged("CPP_ENTITY");
					this.OnCPP_ENTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPP_LOKASI", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CPP_LOKASI
		{
			get
			{
				return this._CPP_LOKASI;
			}
			set
			{
				if ((this._CPP_LOKASI != value))
				{
					this.OnCPP_LOKASIChanging(value);
					this.SendPropertyChanging();
					this._CPP_LOKASI = value;
					this.SendPropertyChanged("CPP_LOKASI");
					this.OnCPP_LOKASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPP_DESC", DbType="VarChar(200)")]
		public string CPP_DESC
		{
			get
			{
				return this._CPP_DESC;
			}
			set
			{
				if ((this._CPP_DESC != value))
				{
					this.OnCPP_DESCChanging(value);
					this.SendPropertyChanging();
					this._CPP_DESC = value;
					this.SendPropertyChanged("CPP_DESC");
					this.OnCPP_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPP_AKTIF", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CPP_AKTIF
		{
			get
			{
				return this._CPP_AKTIF;
			}
			set
			{
				if ((this._CPP_AKTIF != value))
				{
					this.OnCPP_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._CPP_AKTIF = value;
					this.SendPropertyChanged("CPP_AKTIF");
					this.OnCPP_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_ENTITY")]
	public partial class TBL_R_ENTITY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ENTITY_CODE;
		
		private string _ENTITY_NAME;
		
		private string _ENTITY_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTITY_CODEChanging(string value);
    partial void OnENTITY_CODEChanged();
    partial void OnENTITY_NAMEChanging(string value);
    partial void OnENTITY_NAMEChanged();
    partial void OnENTITY_AKTIFChanging(string value);
    partial void OnENTITY_AKTIFChanged();
    #endregion
		
		public TBL_R_ENTITY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ENTITY_CODE
		{
			get
			{
				return this._ENTITY_CODE;
			}
			set
			{
				if ((this._ENTITY_CODE != value))
				{
					this.OnENTITY_CODEChanging(value);
					this.SendPropertyChanging();
					this._ENTITY_CODE = value;
					this.SendPropertyChanged("ENTITY_CODE");
					this.OnENTITY_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY_NAME", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string ENTITY_NAME
		{
			get
			{
				return this._ENTITY_NAME;
			}
			set
			{
				if ((this._ENTITY_NAME != value))
				{
					this.OnENTITY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ENTITY_NAME = value;
					this.SendPropertyChanged("ENTITY_NAME");
					this.OnENTITY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTITY_AKTIF", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ENTITY_AKTIF
		{
			get
			{
				return this._ENTITY_AKTIF;
			}
			set
			{
				if ((this._ENTITY_AKTIF != value))
				{
					this.OnENTITY_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._ENTITY_AKTIF = value;
					this.SendPropertyChanged("ENTITY_AKTIF");
					this.OnENTITY_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_PRODUCT")]
	public partial class TBL_R_PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PRODUCT_CODE;
		
		private string _PRODUCT_ENTITY;
		
		private string _PRODUCT_NAME;
		
		private string _PRODUCT_DESC;
		
		private string _PRODUCT_ACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCT_CODEChanging(string value);
    partial void OnPRODUCT_CODEChanged();
    partial void OnPRODUCT_ENTITYChanging(string value);
    partial void OnPRODUCT_ENTITYChanged();
    partial void OnPRODUCT_NAMEChanging(string value);
    partial void OnPRODUCT_NAMEChanged();
    partial void OnPRODUCT_DESCChanging(string value);
    partial void OnPRODUCT_DESCChanged();
    partial void OnPRODUCT_ACTIVEChanging(string value);
    partial void OnPRODUCT_ACTIVEChanged();
    #endregion
		
		public TBL_R_PRODUCT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PRODUCT_CODE
		{
			get
			{
				return this._PRODUCT_CODE;
			}
			set
			{
				if ((this._PRODUCT_CODE != value))
				{
					this.OnPRODUCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_CODE = value;
					this.SendPropertyChanged("PRODUCT_CODE");
					this.OnPRODUCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ENTITY", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string PRODUCT_ENTITY
		{
			get
			{
				return this._PRODUCT_ENTITY;
			}
			set
			{
				if ((this._PRODUCT_ENTITY != value))
				{
					this.OnPRODUCT_ENTITYChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_ENTITY = value;
					this.SendPropertyChanged("PRODUCT_ENTITY");
					this.OnPRODUCT_ENTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string PRODUCT_NAME
		{
			get
			{
				return this._PRODUCT_NAME;
			}
			set
			{
				if ((this._PRODUCT_NAME != value))
				{
					this.OnPRODUCT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_NAME = value;
					this.SendPropertyChanged("PRODUCT_NAME");
					this.OnPRODUCT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_DESC", DbType="VarChar(200)")]
		public string PRODUCT_DESC
		{
			get
			{
				return this._PRODUCT_DESC;
			}
			set
			{
				if ((this._PRODUCT_DESC != value))
				{
					this.OnPRODUCT_DESCChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_DESC = value;
					this.SendPropertyChanged("PRODUCT_DESC");
					this.OnPRODUCT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ACTIVE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PRODUCT_ACTIVE
		{
			get
			{
				return this._PRODUCT_ACTIVE;
			}
			set
			{
				if ((this._PRODUCT_ACTIVE != value))
				{
					this.OnPRODUCT_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_ACTIVE = value;
					this.SendPropertyChanged("PRODUCT_ACTIVE");
					this.OnPRODUCT_ACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_STOCKPILE")]
	public partial class TBL_R_STOCKPILE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STOCKPILE_CODE;
		
		private string _STOCKPILE_NAME;
		
		private string _STOCKPILE_LOKASI;
		
		private string _STOCKPILE_DESC;
		
		private string _STOCKPILE_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTOCKPILE_CODEChanging(string value);
    partial void OnSTOCKPILE_CODEChanged();
    partial void OnSTOCKPILE_NAMEChanging(string value);
    partial void OnSTOCKPILE_NAMEChanged();
    partial void OnSTOCKPILE_LOKASIChanging(string value);
    partial void OnSTOCKPILE_LOKASIChanged();
    partial void OnSTOCKPILE_DESCChanging(string value);
    partial void OnSTOCKPILE_DESCChanged();
    partial void OnSTOCKPILE_AKTIFChanging(string value);
    partial void OnSTOCKPILE_AKTIFChanged();
    #endregion
		
		public TBL_R_STOCKPILE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKPILE_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STOCKPILE_CODE
		{
			get
			{
				return this._STOCKPILE_CODE;
			}
			set
			{
				if ((this._STOCKPILE_CODE != value))
				{
					this.OnSTOCKPILE_CODEChanging(value);
					this.SendPropertyChanging();
					this._STOCKPILE_CODE = value;
					this.SendPropertyChanged("STOCKPILE_CODE");
					this.OnSTOCKPILE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKPILE_NAME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string STOCKPILE_NAME
		{
			get
			{
				return this._STOCKPILE_NAME;
			}
			set
			{
				if ((this._STOCKPILE_NAME != value))
				{
					this.OnSTOCKPILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STOCKPILE_NAME = value;
					this.SendPropertyChanged("STOCKPILE_NAME");
					this.OnSTOCKPILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKPILE_LOKASI", DbType="VarChar(100)")]
		public string STOCKPILE_LOKASI
		{
			get
			{
				return this._STOCKPILE_LOKASI;
			}
			set
			{
				if ((this._STOCKPILE_LOKASI != value))
				{
					this.OnSTOCKPILE_LOKASIChanging(value);
					this.SendPropertyChanging();
					this._STOCKPILE_LOKASI = value;
					this.SendPropertyChanged("STOCKPILE_LOKASI");
					this.OnSTOCKPILE_LOKASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKPILE_DESC", DbType="VarChar(200)")]
		public string STOCKPILE_DESC
		{
			get
			{
				return this._STOCKPILE_DESC;
			}
			set
			{
				if ((this._STOCKPILE_DESC != value))
				{
					this.OnSTOCKPILE_DESCChanging(value);
					this.SendPropertyChanging();
					this._STOCKPILE_DESC = value;
					this.SendPropertyChanged("STOCKPILE_DESC");
					this.OnSTOCKPILE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCKPILE_AKTIF", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string STOCKPILE_AKTIF
		{
			get
			{
				return this._STOCKPILE_AKTIF;
			}
			set
			{
				if ((this._STOCKPILE_AKTIF != value))
				{
					this.OnSTOCKPILE_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._STOCKPILE_AKTIF = value;
					this.SendPropertyChanged("STOCKPILE_AKTIF");
					this.OnSTOCKPILE_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_UNIT")]
	public partial class TBL_R_UNIT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UNIT_NO;
		
		private string _UNIT_ENTITY;
		
		private string _UNIT_EGI;
		
		private string _UNIT_KONTRAKTOR;
		
		private int _UNIT_DEFAULT_TARE;
		
		private string _UNIT_AKTIF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUNIT_NOChanging(string value);
    partial void OnUNIT_NOChanged();
    partial void OnUNIT_ENTITYChanging(string value);
    partial void OnUNIT_ENTITYChanged();
    partial void OnUNIT_EGIChanging(string value);
    partial void OnUNIT_EGIChanged();
    partial void OnUNIT_KONTRAKTORChanging(string value);
    partial void OnUNIT_KONTRAKTORChanged();
    partial void OnUNIT_DEFAULT_TAREChanging(int value);
    partial void OnUNIT_DEFAULT_TAREChanged();
    partial void OnUNIT_AKTIFChanging(string value);
    partial void OnUNIT_AKTIFChanged();
    #endregion
		
		public TBL_R_UNIT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_NO", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UNIT_NO
		{
			get
			{
				return this._UNIT_NO;
			}
			set
			{
				if ((this._UNIT_NO != value))
				{
					this.OnUNIT_NOChanging(value);
					this.SendPropertyChanging();
					this._UNIT_NO = value;
					this.SendPropertyChanged("UNIT_NO");
					this.OnUNIT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_ENTITY", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string UNIT_ENTITY
		{
			get
			{
				return this._UNIT_ENTITY;
			}
			set
			{
				if ((this._UNIT_ENTITY != value))
				{
					this.OnUNIT_ENTITYChanging(value);
					this.SendPropertyChanging();
					this._UNIT_ENTITY = value;
					this.SendPropertyChanged("UNIT_ENTITY");
					this.OnUNIT_ENTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_EGI", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UNIT_EGI
		{
			get
			{
				return this._UNIT_EGI;
			}
			set
			{
				if ((this._UNIT_EGI != value))
				{
					this.OnUNIT_EGIChanging(value);
					this.SendPropertyChanging();
					this._UNIT_EGI = value;
					this.SendPropertyChanged("UNIT_EGI");
					this.OnUNIT_EGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_KONTRAKTOR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UNIT_KONTRAKTOR
		{
			get
			{
				return this._UNIT_KONTRAKTOR;
			}
			set
			{
				if ((this._UNIT_KONTRAKTOR != value))
				{
					this.OnUNIT_KONTRAKTORChanging(value);
					this.SendPropertyChanging();
					this._UNIT_KONTRAKTOR = value;
					this.SendPropertyChanged("UNIT_KONTRAKTOR");
					this.OnUNIT_KONTRAKTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_DEFAULT_TARE", DbType="Int NOT NULL")]
		public int UNIT_DEFAULT_TARE
		{
			get
			{
				return this._UNIT_DEFAULT_TARE;
			}
			set
			{
				if ((this._UNIT_DEFAULT_TARE != value))
				{
					this.OnUNIT_DEFAULT_TAREChanging(value);
					this.SendPropertyChanging();
					this._UNIT_DEFAULT_TARE = value;
					this.SendPropertyChanged("UNIT_DEFAULT_TARE");
					this.OnUNIT_DEFAULT_TAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_AKTIF", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string UNIT_AKTIF
		{
			get
			{
				return this._UNIT_AKTIF;
			}
			set
			{
				if ((this._UNIT_AKTIF != value))
				{
					this.OnUNIT_AKTIFChanging(value);
					this.SendPropertyChanging();
					this._UNIT_AKTIF = value;
					this.SendPropertyChanged("UNIT_AKTIF");
					this.OnUNIT_AKTIFChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_TARE_UNIT")]
	public partial class TBL_T_TARE_UNIT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TARE_RAW_ID;
		
		private string _TARE_UNIT_NO;
		
		private int _TARE_VALUE;
		
		private System.DateTime _TARE_DATETIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTARE_RAW_IDChanging(string value);
    partial void OnTARE_RAW_IDChanged();
    partial void OnTARE_UNIT_NOChanging(string value);
    partial void OnTARE_UNIT_NOChanged();
    partial void OnTARE_VALUEChanging(int value);
    partial void OnTARE_VALUEChanged();
    partial void OnTARE_DATETIMEChanging(System.DateTime value);
    partial void OnTARE_DATETIMEChanged();
    #endregion
		
		public TBL_T_TARE_UNIT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARE_RAW_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TARE_RAW_ID
		{
			get
			{
				return this._TARE_RAW_ID;
			}
			set
			{
				if ((this._TARE_RAW_ID != value))
				{
					this.OnTARE_RAW_IDChanging(value);
					this.SendPropertyChanging();
					this._TARE_RAW_ID = value;
					this.SendPropertyChanged("TARE_RAW_ID");
					this.OnTARE_RAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARE_UNIT_NO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TARE_UNIT_NO
		{
			get
			{
				return this._TARE_UNIT_NO;
			}
			set
			{
				if ((this._TARE_UNIT_NO != value))
				{
					this.OnTARE_UNIT_NOChanging(value);
					this.SendPropertyChanging();
					this._TARE_UNIT_NO = value;
					this.SendPropertyChanged("TARE_UNIT_NO");
					this.OnTARE_UNIT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARE_VALUE", DbType="Int NOT NULL")]
		public int TARE_VALUE
		{
			get
			{
				return this._TARE_VALUE;
			}
			set
			{
				if ((this._TARE_VALUE != value))
				{
					this.OnTARE_VALUEChanging(value);
					this.SendPropertyChanging();
					this._TARE_VALUE = value;
					this.SendPropertyChanged("TARE_VALUE");
					this.OnTARE_VALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARE_DATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime TARE_DATETIME
		{
			get
			{
				return this._TARE_DATETIME;
			}
			set
			{
				if ((this._TARE_DATETIME != value))
				{
					this.OnTARE_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._TARE_DATETIME = value;
					this.SendPropertyChanged("TARE_DATETIME");
					this.OnTARE_DATETIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_TRANSAKSI_18")]
	public partial class TBL_T_TRANSAKSI_18 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TRANS_RAW_ID;
		
		private string _TRANS_UNIT;
		
		private string _TRANS_ENTITY;
		
		private string _TRANS_CPP;
		
		private string _TRANS_PRODUCT;
		
		private string _TRANS_STOCKPILE;
		
		private string _TRANS_LOADER;
		
		private int _TRANS_GROSS;
		
		private int _TRANS_TARE;
		
		private System.DateTime _TRANS_START_TIMBANG;
		
		private System.DateTime _TRANS_DATETIME;
		
		private System.DateTime _TRANS_UPDATE_AT;
		
		private string _TRANS_OPERATOR;
		
		private string _TRANS_DOCKET_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRANS_RAW_IDChanging(string value);
    partial void OnTRANS_RAW_IDChanged();
    partial void OnTRANS_UNITChanging(string value);
    partial void OnTRANS_UNITChanged();
    partial void OnTRANS_ENTITYChanging(string value);
    partial void OnTRANS_ENTITYChanged();
    partial void OnTRANS_CPPChanging(string value);
    partial void OnTRANS_CPPChanged();
    partial void OnTRANS_PRODUCTChanging(string value);
    partial void OnTRANS_PRODUCTChanged();
    partial void OnTRANS_STOCKPILEChanging(string value);
    partial void OnTRANS_STOCKPILEChanged();
    partial void OnTRANS_LOADERChanging(string value);
    partial void OnTRANS_LOADERChanged();
    partial void OnTRANS_GROSSChanging(int value);
    partial void OnTRANS_GROSSChanged();
    partial void OnTRANS_TAREChanging(int value);
    partial void OnTRANS_TAREChanged();
    partial void OnTRANS_START_TIMBANGChanging(System.DateTime value);
    partial void OnTRANS_START_TIMBANGChanged();
    partial void OnTRANS_DATETIMEChanging(System.DateTime value);
    partial void OnTRANS_DATETIMEChanged();
    partial void OnTRANS_UPDATE_ATChanging(System.DateTime value);
    partial void OnTRANS_UPDATE_ATChanged();
    partial void OnTRANS_OPERATORChanging(string value);
    partial void OnTRANS_OPERATORChanged();
    partial void OnTRANS_DOCKET_IDChanging(string value);
    partial void OnTRANS_DOCKET_IDChanged();
    #endregion
		
		public TBL_T_TRANSAKSI_18()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_RAW_ID", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TRANS_RAW_ID
		{
			get
			{
				return this._TRANS_RAW_ID;
			}
			set
			{
				if ((this._TRANS_RAW_ID != value))
				{
					this.OnTRANS_RAW_IDChanging(value);
					this.SendPropertyChanging();
					this._TRANS_RAW_ID = value;
					this.SendPropertyChanged("TRANS_RAW_ID");
					this.OnTRANS_RAW_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_UNIT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TRANS_UNIT
		{
			get
			{
				return this._TRANS_UNIT;
			}
			set
			{
				if ((this._TRANS_UNIT != value))
				{
					this.OnTRANS_UNITChanging(value);
					this.SendPropertyChanging();
					this._TRANS_UNIT = value;
					this.SendPropertyChanged("TRANS_UNIT");
					this.OnTRANS_UNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_ENTITY", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TRANS_ENTITY
		{
			get
			{
				return this._TRANS_ENTITY;
			}
			set
			{
				if ((this._TRANS_ENTITY != value))
				{
					this.OnTRANS_ENTITYChanging(value);
					this.SendPropertyChanging();
					this._TRANS_ENTITY = value;
					this.SendPropertyChanged("TRANS_ENTITY");
					this.OnTRANS_ENTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_CPP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TRANS_CPP
		{
			get
			{
				return this._TRANS_CPP;
			}
			set
			{
				if ((this._TRANS_CPP != value))
				{
					this.OnTRANS_CPPChanging(value);
					this.SendPropertyChanging();
					this._TRANS_CPP = value;
					this.SendPropertyChanged("TRANS_CPP");
					this.OnTRANS_CPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_PRODUCT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TRANS_PRODUCT
		{
			get
			{
				return this._TRANS_PRODUCT;
			}
			set
			{
				if ((this._TRANS_PRODUCT != value))
				{
					this.OnTRANS_PRODUCTChanging(value);
					this.SendPropertyChanging();
					this._TRANS_PRODUCT = value;
					this.SendPropertyChanged("TRANS_PRODUCT");
					this.OnTRANS_PRODUCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_STOCKPILE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TRANS_STOCKPILE
		{
			get
			{
				return this._TRANS_STOCKPILE;
			}
			set
			{
				if ((this._TRANS_STOCKPILE != value))
				{
					this.OnTRANS_STOCKPILEChanging(value);
					this.SendPropertyChanging();
					this._TRANS_STOCKPILE = value;
					this.SendPropertyChanged("TRANS_STOCKPILE");
					this.OnTRANS_STOCKPILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_LOADER", DbType="VarChar(10)")]
		public string TRANS_LOADER
		{
			get
			{
				return this._TRANS_LOADER;
			}
			set
			{
				if ((this._TRANS_LOADER != value))
				{
					this.OnTRANS_LOADERChanging(value);
					this.SendPropertyChanging();
					this._TRANS_LOADER = value;
					this.SendPropertyChanged("TRANS_LOADER");
					this.OnTRANS_LOADERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_GROSS", DbType="Int NOT NULL")]
		public int TRANS_GROSS
		{
			get
			{
				return this._TRANS_GROSS;
			}
			set
			{
				if ((this._TRANS_GROSS != value))
				{
					this.OnTRANS_GROSSChanging(value);
					this.SendPropertyChanging();
					this._TRANS_GROSS = value;
					this.SendPropertyChanged("TRANS_GROSS");
					this.OnTRANS_GROSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_TARE", DbType="Int NOT NULL")]
		public int TRANS_TARE
		{
			get
			{
				return this._TRANS_TARE;
			}
			set
			{
				if ((this._TRANS_TARE != value))
				{
					this.OnTRANS_TAREChanging(value);
					this.SendPropertyChanging();
					this._TRANS_TARE = value;
					this.SendPropertyChanged("TRANS_TARE");
					this.OnTRANS_TAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_START_TIMBANG", DbType="DateTime NOT NULL")]
		public System.DateTime TRANS_START_TIMBANG
		{
			get
			{
				return this._TRANS_START_TIMBANG;
			}
			set
			{
				if ((this._TRANS_START_TIMBANG != value))
				{
					this.OnTRANS_START_TIMBANGChanging(value);
					this.SendPropertyChanging();
					this._TRANS_START_TIMBANG = value;
					this.SendPropertyChanged("TRANS_START_TIMBANG");
					this.OnTRANS_START_TIMBANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_DATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime TRANS_DATETIME
		{
			get
			{
				return this._TRANS_DATETIME;
			}
			set
			{
				if ((this._TRANS_DATETIME != value))
				{
					this.OnTRANS_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._TRANS_DATETIME = value;
					this.SendPropertyChanged("TRANS_DATETIME");
					this.OnTRANS_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_UPDATE_AT", DbType="DateTime NOT NULL")]
		public System.DateTime TRANS_UPDATE_AT
		{
			get
			{
				return this._TRANS_UPDATE_AT;
			}
			set
			{
				if ((this._TRANS_UPDATE_AT != value))
				{
					this.OnTRANS_UPDATE_ATChanging(value);
					this.SendPropertyChanging();
					this._TRANS_UPDATE_AT = value;
					this.SendPropertyChanged("TRANS_UPDATE_AT");
					this.OnTRANS_UPDATE_ATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_OPERATOR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TRANS_OPERATOR
		{
			get
			{
				return this._TRANS_OPERATOR;
			}
			set
			{
				if ((this._TRANS_OPERATOR != value))
				{
					this.OnTRANS_OPERATORChanging(value);
					this.SendPropertyChanging();
					this._TRANS_OPERATOR = value;
					this.SendPropertyChanged("TRANS_OPERATOR");
					this.OnTRANS_OPERATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANS_DOCKET_ID", DbType="VarChar(200)")]
		public string TRANS_DOCKET_ID
		{
			get
			{
				return this._TRANS_DOCKET_ID;
			}
			set
			{
				if ((this._TRANS_DOCKET_ID != value))
				{
					this.OnTRANS_DOCKET_IDChanging(value);
					this.SendPropertyChanging();
					this._TRANS_DOCKET_ID = value;
					this.SendPropertyChanged("TRANS_DOCKET_ID");
					this.OnTRANS_DOCKET_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
